development:
  adapter: postgresql
  encoding: unicode
  database: courier_service_development
  username: shaileshjain
  password: shailujain123
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: courier_service_development
  username: shaileshjain
  password: shailujain123
  host: localhost
  port: 5432
  pool: 5